export const CONSTRUCTOR_ADD_INGREDIENT = 'CONSTRUCTOR_ADD_INGREDIENT';
export const CONSTRUCTOR_ADD_OR_CHANGE_BUN = 'CONSTRUCTOR_ADD_OR_CHANGE_BUN';
export const CONSTRUCTOR_SORT_INGREDIENTS = 'CONSTRUCTOR_SORT_INGREDIENTS';
export const CONSTRUCTOR_DELETE_INGREDIENT = 'CONSTRUCTOR_DELETE_INGREDIENT';
export const CONSTRUCTOR_RESET_INGREDIENTS = 'CONSTRUCTOR_RESET_INGREDIENTS';
