export const POST_CONSTRUCTOR_ITEMS_SUCCESS = 'POST_CONSTRUCTOR_ITEMS_SUCCESS';
export const POST_CONSTRUCTOR_ITEMS_FAILED = 'POST_CONSTRUCTOR_ITEMS_FAILED';
export const ORDER_NUMBER_RESET = 'ORDER_NUMBER_RESET';
