export const USER_RESET: 'USER_RESET' = 'USER_RESET';
export const USER_SET: 'USER_SET' = 'USER_SET';
export const USER_REFRESH: 'USER_REFRESH' = 'USER_REFRESH';
export const USER_CHANGE_DATA: 'USER_CHANGE_DATA' = 'USER_CHANGE_DATA'
